[build]
  base = "sanity"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://tiny-froyo-134e27.netlify.app/*"
  to = "https://content.christopherrouleau.com/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/"
  status = 200