import './globals.css';
import localFont from 'next/font/local';
import Banner from '@/components/Banner';
import Footer from '@/components/Footer';

const Basecoat = localFont({
	src: [
		{
			path: '../assets/fonts/basecoat.otf',
			weight: '400',
			style: 'normal',
		},
		{
			path: '../assets/fonts/basecoat-light.otf',
			weight: '300',
			style: 'normal',
		},
		{
			path: '../assets/fonts/basecoat-bold.otf',
			weight: '700',
			style: 'normal',
		},
	],
});

export const metadata = {
	title: 'Christopher Rouleau',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={Basecoat.className}>
			<body>
				<Banner />
				{children}
				<Footer />
			</body>
		</html>
	);
}
